kuskoman/logstash-exporter

scripts/create_release_notes.sh

The script will no longer append merge commits to release_notes.txt
example:
```
Release Notes:
Since the last tag (v0.1.0), the following changes have been made:
Add codecov to unit tests
Add CodeQL workflow
Bump golang from 1.20.0-alpine3.17 to 1.20.1-alpine3.17
Bump github.com/prometheus/common from 0.37.0 to 0.40.0
Add dependabot config
Use checkout@v3 instead of v2
Add SHA256 sum generation (#20)
Extract github user to env variable (#18)
Rename NodestatsResponse to NodeStatsResponse
Improve nodestats collector test
Change go version used in workflow
Remove unnecessary fetcher package
Improve node info test to check if all metrics are present
Add expose to Dockerfile
Update metrics in README
Add code for checking if logstash is up
```

Remove merge commits from release notes

---

Makefile
README.md
chart/templates/_helpers.tpl
chart/templates/deployment.yaml
chart/values.yaml

1. Fixes the draft Helm chart, which had indentation issues, and several pod-level configs which needed to be in the inner-level template. (tested with Helm v3.11.2)
2. Fixes `livenessProbe` to use the `/health` endpoint and default service port.
3. The deployment's `fullname` would default to `logstash-exporter-logstash-exporter`, so I borrowed [Helm's default template helper](https://github.com/helm/helm/blob/e007c900ce5f2233c8583565d5ba1b0433b1a213/pkg/chartutil/create.go#L433-L449) for this. This can be manually set via `values.yaml`.
4. Added `docker buildx` to the Makefile for the zen of running locally on an M1, but using on an AMD64 K8s cluster. Also for AWS Graviton instances.

Helm Chart Fixes + Multi-Arch Docker build

---

docker-compose.yml

Resolves #97. Passes the `--config.reload.automatic` to the [entrypoint used in the official image](https://github.com/elastic/logstash/blob/main/docker/data/logstash/bin/docker-entrypoint).

Docker-compose: Logstash supports hot config reload

---

fetcher/responses/__snapshots__/nodestats_response_test.snap
fetcher/responses/nodestats_response.go
fixtures/node_stats.json

Resolves #96. The `PipelineReloadResponse.pipelines.reloads.last_error` is defined in `fetcher/responses/nodestats_response.go` as a string, however it is an object with `message` and `backtrace` properties.
This contains the fix, and an update snap of the unmarshalled struct. Some other values in the fixture exist due to cherry-picking from the next PR.

Fix last_error field not being properly defined

---

Makefile

`docker buildx` needs `--push` to do anything useful. And I'm pushing to ECR, which requires full image path naming. So this adds `DOCKER_IMG` which will default to `logstash-exporter`.

Adds DOCKER_IMG ENV to Makefile

---

docker-compose.yml

I found out that elasticsearch is taking about 30gb of ram on my work machine, which takes nearly all of my resources. This does not happen on all machines, but this fixes it on this specific one.

Limit Java cheap size for dev docker-compose

---

Makefile
cmd/exporter/main.go
config/version.go
config/version_test.go
server/versioninfo_test.go

Adds a simple semantic version configuration and flag to print the version and exit. Test coverage is present for the general additions to version info, however here are some additional test cases I ran manually.
Version on the current branch
```
; make out/main-darwin                          
CGO_ENABLED=0 GOOS=darwin go build -a -installsuffix cgo -ldflags="-s -w -X 'github.com/kuskoman/logstash-exporter/config.Version=mikey/version-command' -X 'github.com/kuskoman/logstash-exporter/config.SemanticVersion=v1.5.4-3-g5fd1' -X 'github.com/kuskoman/logstash-exporter/config.GitCommit=5fd14993d6e767e0ba81c4aac0bdeedc5658a6a0' -X 'github.com/kuskoman/logstash-exporter/config.BuildDate=2023-10-13T21:59:38UTC'" -o out/main-darwin cmd/exporter/main.go
; ./out/main-darwin -version
v1.5.4-3-g5fd1 …
```

Add support for a version command to check the binary version

---

Dockerfile

Modification for #200, reuse `nobody` entry in `/etc/passwd` from alpine image to allow the application to run with the `nobody` user.

Update Dockerfile to run as "nobody" user

---

collectors/collector_manager.go
collectors/collector_manager_test.go
collectors/nodeinfo/nodeinfo_collector_test.go
collectors/nodestats/nodestats_collector_test.go
config/exporter_config.go
fetcher/logstash_client/client.go
fetcher/logstash_client/client_test.go
fetcher/logstash_client/queries_test.go

The PR removes code related to #202 
Basically, since all instances now have hostname attached, a simple proxy should be able to solve the issue
I took some time to implement custom labeling, but it required way more logic than it gives benefits:
- config had to have custom logic for:
a. verifying label consistency
b. sorting label keys
c. sorting label values according to keys order
- client had to preserve either reference to config or reference to sorted slice of keys that are later on used to determine values to add to each and every metric
- since #79 was closed, there is no simple way that i know to treat these labels as const labels. therefore the logic is mixed with existing variableLabels logic which makes code way more unreadable than it currently is
I believe there are existing …

Remove label logic from client

---

.github/workflows/go-application.yml
chart/templates/configmap.yaml
chart/values.yaml

Fix nident error in configmap setting, improve Helm testing workflow

---

cmd/exporter/main.go

Previously log was used if .env file could not be found. This behaviour was inconsistent, so after the change application is supposed to wait for getting slog configuration, before printing an error using regular log package

Unify slog usage

---

internal/collectors/nodestats/pipeline_subcollector.go
internal/prometheus_helper/prometheus_helper_test.go

Improve code readability in pipelines subcollector

---

scripts/add_metrics_to_readme.sh

Fix `add_metrics_to_readme.sh` script

---

scripts/verify_metrics.sh

Fix `verify_metrics.sh` script 

---

README.md
scripts/add_metrics_to_readme.sh

Add successful timestamp to metrics script and fix script

---

internal/collectors/nodestats/nodestats_collector.go
internal/collectors/nodestats/pipeline_subcollector.go
internal/fetcher/responses/__snapshots__/nodestats_response_test.snap
internal/fetcher/responses/nodestats_response.go
internal/prometheus_helper/prometheus_helper.go
internal/prometheus_helper/prometheus_helper_test.go

1. Remove UInt type -> some values may hold -1 instead
2. Use UInt64 for memory-related values
Relates to #314

Change data types to more reliable

---

internal/collectors/nodestats/pipeline_subcollector.go
internal/fetcher/responses/__snapshots__/nodestats_response_test.snap
internal/fetcher/responses/nodestats_response.go

Change datatype for pipeline response

---

chart/templates/deployment.yaml

The indentation should be 10 instead of 12 to make yamllint not complain.

Fix intendation of securityContext

---

chart/README.md
chart/schema.json
chart/templates/deployment.yaml
chart/values.yaml

The available options of pod and container securityContext can differ. For example readOnlyRootFilesystem only applies to containers.
This pr allows setting securityContext for pods and containers while trying to keep backword compability in mind.
The intendation for some elements also was adjusted to make yamllint happy. Some elements where indented by 12 spaces instead of 10.

Allow specifying pod and container securityContext and fix intendations to make yamllint happy

---

cmd/exporter/main.go
collectors/collector_manager.go
collectors/collector_manager_test.go
config/http_config.go
config/http_config_test.go
fetcher/logstash_client/client.go
fetcher/logstash_client/client_test.go
fetcher/logstash_client/queries_test.go

after upgrade eck operator to 2.13
the logstash create by operator will default enable ssl for http endpoint 9600
and the exporter will got this error
so i add a config to make a InsecureSkipVerify to http client to prevent this problem

add HTTP_INSECURE config
