kuskoman/logstash-exporter

README.md, collectors/nodeinfo/nodeinfo_collector.go
=> Add code for checking if logstash is up

README.md, cmd/exporter/main.go, config/server_config.go, server/server.go, server/server_test.go
closes #2 
may be useful for windows users
=> Allow to specify listen host

collectors/nodeinfo/nodeinfo_collector_test.go
TODO: do the same with node stats
=> Improve node info test to check if all metrics are present

.github/workflows/go-application.yml, README.md
Add SHA256 checksum files to releases
Closes #16
=> Add SHA256 sum generation

.github/workflows/go-application.yml
=> Use checkout@v3 instead of v2

.github/workflows/go-application.yml
=> Append release notes to releases

scripts/create_release_notes.sh
=> Allow to create release notes from branch

.github/workflows/go-application.yml, scripts/create_release_notes.sh
Proof: https://github.com/kuskoman/logstash-exporter/actions/runs/4335529851
=> Fix path for binary upload and checkout for release_notes

server/healthcheck.go
source: https://youtu.be/Oe6L5ZmqCDE?t=611
=> Refactor healthcheck to use context

cmd/exporter/main.go, config/env_helper.go, config/env_helper_test.go, config/logstash_config.go, config/prometheus_config.go, config/server_config.go, fetcher/logstash_client/client.go, fetcher/logstash_client/queries.go, fetcher/responses/nodeinfo_response.go, fetcher/responses/nodestats_response.go, prometheus_helper/prometheus_helper.go, prometheus_helper/prometheus_helper_test.go
Refactor multiple files, add 100% test coverage to the project
=> More refactor, 100% test coverage

.github/workflows/go-application.yml
=> Publish tag images to ghcr.io

Dockerfile, Makefile, cmd/exporter/main.go, config/version.go, config/version_test.go, server/server.go, server/versioninfo.go, server/versioninfo_test.go
Add /version endpoint that returns build information
=> Add build/version info to the application

chart/Chart.yaml, chart/README.md, chart/schema.json, chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/values.yaml, scripts/release_tag.sh
=> Implement application and chart versioning script

.github/workflows/go-application.yml, .helm/logstash-integration-test-chart/values.yaml
This way we will test new image and Helm chart at the same time
=> Execute Kubernetes tests on image from current build

collectors/nodestats/pipeline_subcollector.go
=> Fixes #107 incorrect logstash_stats_pipeline_plugin_events_in

.github/workflows/go-application.yml, Makefile
=> Fix version parameter in binaries from CI

Makefile
=> Implement 'make help' command

README.md
=> Add info about log level to readme

docker-compose.yml
Currently no automatic update is configured
=> Update image tags in docker-compose

.github/workflows/go-application.yml, go.mod, go.sum
- lint gomod
- upgrade golangci-lint version
=> Upgrade linters

.docker/logstash.conf
Throttle messages using ruby code
=> Throttle elasticsearch messages

.docker/grafana.ini, .docker/provisioning/datasources/all.yml, docker-compose.yml
In order to make debugging problems with the exporter easier I am adding Grafana to the local development stack
=> Add Grafana to local development stack

.github/workflows/go-application.yml, Makefile
Fix Issue #136 
Run this on my fork buildx seems to be working but I can't test the rest of the pipeline integrations 
https://github.com/arousseau-coveo/logstash-exporter/actions/runs/6027420067/job/16352636745
=> Add building multi-arch image to pipeline

README.md, collectors/nodestats/pipeline_subcollector.go
=> Change dead_letter_queue_max_size_in_bytes / size_in_bytes from counter to gauge metrics

.github/workflows/go-application.yml, Makefile
=> Add ARM64 pipeline

.github/workflows/go-application.yml
=> Add ARM build to the application

cmd/exporter/main.go, config/exporter_config.go, config/exporter_config_test.go, config/http_config.go, config/slog_config.go, config/slog_config_test.go
=> Implement log level and format configuration through YAML (resolves #224)

chart/templates/service.yaml
* fix intendation in line 9
* change indent to nindent in line 10
Closes #226
=> Fix intendation issue in Helm chart

chart/templates/service.yaml
=> Fix intendation in service.yaml

Makefile
=> Add building ARM binary to the Makefile

LICENSE
=> Change year in LICENSE file to 2024

Makefile, scripts/add_descriptions_to_readme.sh
=> Fix warning displayed when using make help command

internal/collectors/nodeinfo/nodeinfo_collector_test.go, internal/collectors/nodestats/nodestats_collector_test.go, internal/collectors/nodestats/pipeline_subcollector_test.go, internal/prometheus_helper/prometheus_helper_test.go, pkg/config/slog_config_test.go, pkg/config/version_test.go, pkg/manager/collector_manager_test.go
Linter should be configured to take care of it
=> Lowercase all errors to unify standard across all tests

Dockerfile, README.md
=> Dockerfile enhancement

Dockerfile
Move stuff related to passwd file higher, to improve caching
=> Change order of commands in Dockerfile

docker-compose.yml, scripts/add_metrics_to_readme.sh
=> Add unsuccessful metrics to docs metrics

Makefile, README.md, collectors/nodestats/nodestats_collector_test.go, docker-compose.yml, fetcher/responses/__snapshots__/nodeinfo_response_test.snap, fetcher/responses/__snapshots__/nodestats_response_test.snap, fixtures/node_info.json, fixtures/node_stats.json
First of the PRs related to #365, for now i am only adding fixtures, to separate the concerns of the PRs
=> Update snapshots and fixtures to match Logstash 8.15

internal/collectors/nodeinfo/nodeinfo_collector.go
=> Fix "UP" collector metric type

chart/README.md, chart/schema.json, chart/values.yaml
Fix after change #391 
Relates to #409
=> Fix invalid schema in helm chart after change in code

.gitignore, internal/collectors/nodeinfo/nodeinfo_collector.go, internal/collectors/nodeinfo/nodeinfo_collector_test.go, internal/collectors/nodestats/nodestats_collector.go, internal/collectors/nodestats/nodestats_collector_test.go, internal/collectors/nodestats/pipeline_subcollector.go, internal/fetcher/logstash_client/client.go, internal/fetcher/logstash_client/client_test.go, internal/fetcher/logstash_client/queries_test.go, internal/prometheus_helper/prometheus_helper.go, internal/prometheus_helper/prometheus_helper_test.go, pkg/collector_manager/collector_manager.go, pkg/config/exporter_config.go
=> Add names to instances

HELM-DEPLOY.md, README.md, STANDALONE.md, chart/README.md
Utilize ClaudeAI to generate docs
Closing #297 
Closing #298
=> Add documentation for standalone and Helm usage

chart/README.md, chart/schema.json, chart/templates/configmap.yaml, chart/values.yaml
=> Try to fix configmap for instances one more time

README.md
-+ /health → /healthcheck
++ /version
++ /*
=> Update README.md: Correct endpoints list
